image: golang:alpine

stages:
  - build

Build Alpine:
  stage: build
  script:
    - apk add --update git
    - ln -s /builds /go/src/gitlab.com
    - cd /go/src/gitlab.com/${CI_PROJECT_PATH}
    - go get ./...
    - go build
  artifacts:
    untracked: true