image: golang:alpine

stages:
  - build

before_script:
  - go get github.com/tools/godep
  - ln -s /builds /go/src/gitlab.com
  - cd /go/src/gitlab.com/${CI_PROJECT_PATH}

build-my-project:
  stage: build
  script:
    - godep restore
    - godep go build
