image: golang:alpine

stages:
  - build

before_script:
  - apk add --update git
  - ln -s /builds /go/src/gitlab.com
  - cd /go/src/gitlab.com/${CI_PROJECT_PATH}

build-my-project:
  stage: build
  script:
    - go get ./...
    - go build
